// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PBMission4.Models;

namespace PBMission4.Migrations
{
    [DbContext(typeof(MovieContext))]
    partial class MovieContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("PBMission4.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Comedy"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Horror/Suspense"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Drama"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Family"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Miscellaneous"
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryName = "Television"
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryName = "VHS"
                        },
                        new
                        {
                            CategoryId = 8,
                            CategoryName = "Action/Adventure"
                        });
                });

            modelBuilder.Entity("PBMission4.Models.MovieSubmitModel", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ushort>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieId");

                    b.HasIndex("CategoryId");

                    b.ToTable("MovieSubmissions");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            CategoryId = 1,
                            Director = "Adam McKay",
                            Edited = false,
                            Rating = "PG-13",
                            Title = "Anchorman",
                            Year = (ushort)2004
                        },
                        new
                        {
                            MovieId = 2,
                            CategoryId = 1,
                            Director = "Edgar Wright",
                            Edited = false,
                            Rating = "PG-13",
                            Title = "Scott Pilgrim Vs. The World",
                            Year = (ushort)2010
                        },
                        new
                        {
                            MovieId = 3,
                            CategoryId = 2,
                            Director = "John Carpenter",
                            Edited = false,
                            Rating = "PG-13",
                            Title = "The Thing",
                            Year = (ushort)1982
                        });
                });

            modelBuilder.Entity("PBMission4.Models.MovieSubmitModel", b =>
                {
                    b.HasOne("PBMission4.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
