// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PBMission4.Models;

namespace PBMission4.Migrations
{
    [DbContext(typeof(MovieContext))]
    [Migration("20220124232307_First")]
    partial class First
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("PBMission4.Models.MovieSubmitModel", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ushort>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieId");

                    b.ToTable("MovieSubmissions");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            Category = "Comedy",
                            Director = "Adam McKay",
                            Edited = false,
                            Rating = "PG-13",
                            Title = "Anchorman",
                            Year = (ushort)2004
                        },
                        new
                        {
                            MovieId = 2,
                            Category = "Comedy",
                            Director = "Edgar Wright",
                            Edited = false,
                            Rating = "PG-13",
                            Title = "Scott Pilgrim Vs. The World",
                            Year = (ushort)2010
                        },
                        new
                        {
                            MovieId = 3,
                            Category = "Horror/Suspense",
                            Director = "John Carpenter",
                            Edited = false,
                            Rating = "PG-13",
                            Title = "The Thing",
                            Year = (ushort)1982
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
